


development:
  adapter: postgresql
  encoding: unicode
  database: dfihue9i959bua
  pool: 5
  host: ec2-54-225-103-132.compute-1.amazonaws.com
  port: 5432
  username: evbouuvyrgnlqj
  password: 6kSDZu9BJ0SSOdfrrhedGWEGYL

test:
  adapter: postgresql
  encoding: unicode
  database: dfihue9i959bua
  pool: 5
  post: 5432
  host: ec2-54-225-103-132.compute-1.amazonaws.com
  username: evbouuvyrgnlqj
  password: 6kSDZu9BJ0SSOdfrrhedGWEGYL

