


development:
  adapter: postgresql
  encoding: unicode
  database: valentine_development
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 1988iloveyou

test:
  adapter: postgresql
  encoding: unicode
  database: valentine_test
  pool: 5
  post: 5432
  host: localhost
  username: postgres
  password: 1988iloveyou

production:
  adapter: postgresql
  encoding: unicode
  database: valentine_production
  pool: 5
  post: 5432
  host: localhost
  username: postgres
  password: 1988iloveyou